#!/usr/bin/env python
'''
A CLI tool for merging yaml files in a directory

'''
from __future__ import print_function

import sys
import logging

import yamlmerge

if __name__ == '__main__':
    yamlmerge.cli()
